name: update build cache (local)
on:
  workflow_dispatch:

# orig https://github.com/yury-sannikov/awg-openwrt/blob/master/.github/workflows/build-module.yml
# passwall from https://github.com/xiaorouji/openwrt-passwall/blob/main/.github/workflows/Auto%20compile%20with%20openwrt%20sdk.yml
# 3proxy https://github.com/osnosn/3proxy-openwrt
# helloworld https://github.com/fw876/helloworld

jobs:
  build:
    name: "v${{ matrix.build_env.tag }} - ${{ matrix.build_env.pkgarch}} :: ${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}} build"
    runs-on: [self-hosted, ubuntu]
    # runs-on: ubuntu-latest
    permissions:
      actions: write
    strategy:
      matrix:
        build_env:
          - tag: "23.05.0"
            pkgarch: mipsel_24kc
            target: ramips
            subtarget: mt7621
            vermagic: "9c242f353867f49a96054ff8c9f2c460"
          # - tag: "23.05.2"
          #   pkgarch: mipsel_24kc
          #   target: ramips
          #   subtarget: mt7621
          #   vermagic: "9c242f353867f49a96054ff8c9f2c460"  

    steps:
      - name: Clean runner workspace directory
        uses: bhargavms/action-clean-runner-workspace@1.0
      - name: runrunrun
        run: |
            ls -ls
      - name: Restore cache openwrt-cache-${{ matrix.build_env.tag }}-${{ matrix.build_env.target}}-${{ matrix.build_env.subtarget}}
        id: openwrt-cache
        uses: khj809/github-action-cache-local-fs@v1
        with:
          path: ./
          key: openwrt-cache-${{ matrix.build_env.tag }}-${{ matrix.build_env.target}}-${{ matrix.build_env.subtarget}}
          cache-base-path: /root/action-cache
      # - name: Cache Tools and Kernel actions/cache@v4
      #   id: cache-tools-kernel
      #   uses: actions/cache@v4
      #   env:
      #     cache-name: "cache-tools-kernel-${{ matrix.build_env.tag }}-${{ matrix.build_env.pkgarch}}-${{ matrix.build_env.target}}-${{ matrix.build_env.subtarget}}"
      #   with:
      #     path: "**"
      #     key: ${{ runner.os }}-build-vm4-${{ env.cache-name }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-vm4-cache-tools-kernel-${{ matrix.build_env.tag }}-${{ matrix.build_env.pkgarch}}-    
      # - name: runrunrun actions/cache@v4
      #   if: ${{ steps.cache-tools-kernel.outputs.cache-hit != 'true' }}
      #   run: |
      #       ls -la
      - name: runrunrun khj809/github-action-cache-local-fs@v1
        if: steps.openwrt-cache.outputs.cache-hit != 'true'
        run: |
            ls -la
      - name: Checkout openwrt
        continue-on-error: true
        run: |    
          git clone --depth 1 --branch v${{ matrix.build_env.tag }} https://github.com/openwrt/openwrt.git .
      - name: update openwrt
        run: |    
          git pull --depth 1
      - name: configs and feeds
        run: |
          wget https://downloads.openwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}/feeds.buildinfo -O feeds.conf
          wget https://downloads.openwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}/config.buildinfo -O .config
          ./scripts/feeds update -a && ./scripts/feeds install -a
          make defconfig
      - name: tools build
        run: |    
          make tools/install -i -j `nproc`
      - name: build toolchain
        run: |
          make toolchain/install  -i -j `nproc`
      - name: build linux
        run: |    
          make target/linux/compile  -i -j `nproc`
      - name: runrunrun
        run: |
            ls -la

 
