name: update build cache (local)
on:
  workflow_dispatch:

# orig https://github.com/yury-sannikov/awg-openwrt/blob/master/.github/workflows/build-module.yml
# passwall from https://github.com/xiaorouji/openwrt-passwall/blob/main/.github/workflows/Auto%20compile%20with%20openwrt%20sdk.yml
# 3proxy https://github.com/osnosn/3proxy-openwrt
# helloworld https://github.com/fw876/helloworld

jobs:
  build:
    name: "v${{ matrix.build_env.tag }} - ${{ matrix.build_env.pkgarch}} :: ${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}} build"
    runs-on: [self-hosted, ubuntu]
    # runs-on: ubuntu-latest
    permissions:
      actions: write
    strategy:
      matrix:
        build_env:
          - tag: "23.05.0"
            pkgarch: mipsel_24kc
            target: ramips
            subtarget: mt7621
            vermagic: "9c242f353867f49a96054ff8c9f2c460"
          # - tag: "23.05.2"
          #   pkgarch: mipsel_24kc
          #   target: ramips
          #   subtarget: mt7621
          #   vermagic: "9c242f353867f49a96054ff8c9f2c460"  

    steps:
      - name: Clean runner workspace directory
        uses: bhargavms/action-clean-runner-workspace@1.0
  
      - name: Cache nipeharefa/gh-actions-local-cache
        uses: nipeharefa/gh-actions-local-cache@main #https://github.com/nipeharefa/gh-actions-local-cache
        with:
          path: |
            ./
          key: openwrt-cache-${{ matrix.build_env.tag }}-${{ matrix.build_env.target}}-${{ matrix.build_env.subtarget}}
          storage: /root/openwrt-cache-${{ matrix.build_env.tag }}-${{ matrix.build_env.target}}-${{ matrix.build_env.subtarget}}
      # - name: Cache MasterworksIO/action-local-cache
      #   id: openwrt-cache
      #   uses: MasterworksIO/action-local-cache@2 # https://github.com/MasterworksIO/action-local-cache
      #   with:
      #     path: './'
      #     key: 'openwrt-cache-${{ matrix.build_env.tag }}-${{ matrix.build_env.target}}-${{ matrix.build_env.subtarget}}'
      #     # strategy: copy-immutable
      # - name: Cache actions/cache
      #   id: cache-tools-kernel
      #   uses: actions/cache@v4
      #   env:
      #     cache-name: "cache-tools-kernel-${{ matrix.build_env.tag }}-${{ matrix.build_env.pkgarch}}-${{ matrix.build_env.target}}-${{ matrix.build_env.subtarget}}"
      #   with:
      #     path: "**"
      #     key: ${{ runner.os }}-build-vm4-${{ env.cache-name }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-vm4-cache-tools-kernel-${{ matrix.build_env.tag }}-${{ matrix.build_env.pkgarch}}-
      # - name: test actions/cache@v4
      #   run: ls -la
      #   if: steps.openwrt-cache.outputs.cache-hit != 'true'
      # - name: test MasterworksIO/action-local-cache
      #   run: ls -la
      #   if: ${{ steps.cache-tools-kernel.outputs.cache-hit != 'true' }}
      # - name: Checkout openwrt
      #   uses: actions/checkout@v4
      #   with:
      #     repository: openwrt/openwrt
      #     ref: v${{ matrix.build_env.tag }}
      #     fetch-depth: 1
      #     clean: 'true'
      - name: Checkout openwrt
        run: |    
          git clone --depth 1 --branch v${{ matrix.build_env.tag }} https://github.com/openwrt/openwrt.git .
      - name: Checkout openwrt
        run: |    
          git pull --depth 1
      # - name: configs and feeds
      #   run: |
      #     wget https://downloads.openwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}/feeds.buildinfo -O feeds.conf
      #     wget https://downloads.openwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}}/config.buildinfo -O .config
      #     ./scripts/feeds update -a && ./scripts/feeds install -a
      #     make defconfig
      # - name: tools build
      #   run: |    
      #     make tools/install -i -j `nproc`
      # - name: build toolchain
      #   run: |
      #     make toolchain/install  -i -j `nproc`
      # - name: build linux
      #   run: |    
      #     make target/linux/compile  -i -j `nproc`
      - name: runrunrun
        run: |
            ls -la

 
